# Generated by Django 6.0.4 on 2026-10-08 21:28

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "legal_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="NIT / identificación tributaria",
                    ),
                ),
                (
                    "vertical",
                    models.CharField(
                        choices=[
                            ("generic", "GestorPro (general)"),
                            ("bakery", "Miga (panaderías)"),
                        ],
                        default="generic",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activa"), ("suspended", "Suspendida")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("timezone", models.CharField(default="America/Bogota", max_length=64)),
                ("currency", models.CharField(default="COP", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
                "ordering": ["-is_default", "name"],
                "abstract": False,
                "base_manager_name": "all_tenants",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "name"),
                        name="location_unique_name_per_tenant",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("tenant",),
                        name="location_single_default_per_tenant",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
