# Generated by Django 6.0.4 on 2026-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="dirección"),
        ),
        migrations.AlterField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="activo"),
        ),
        migrations.AlterField(
            model_name="location",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="principal"),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=120, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="location",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="teléfono"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="dirección"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="ciudad"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="currency",
            field=models.CharField(default="COP", max_length=3, verbose_name="moneda"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="legal_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="razón social"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="logo"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(max_length=200, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="teléfono"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[("active", "Activa"), ("suspended", "Suspendida")],
                default="active",
                max_length=20,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="timezone",
            field=models.CharField(
                default="America/Bogota", max_length=64, verbose_name="zona horaria"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="vertical",
            field=models.CharField(
                choices=[
                    ("generic", "GestorPro (general)"),
                    ("bakery", "Miga (panaderías)"),
                ],
                default="generic",
                max_length=20,
                verbose_name="vertical",
            ),
        ),
    ]
