# Generated by Django 6.0.4 on 2026-10-09 13:57

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0002_alter_location_address_alter_location_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor_label", models.CharField(max_length=254)),
                ("action", models.CharField(max_length=80)),
                (
                    "entity_type",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("entity_id", models.CharField(blank=True, default="", max_length=64)),
                ("summary", models.CharField(max_length=300)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Registro de auditoría",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_tenants",
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="audit_audit_tenant__1d7666_idx",
                    ),
                    models.Index(
                        fields=["tenant", "action"],
                        name="audit_audit_tenant__b14d1a_idx",
                    ),
                    models.Index(
                        fields=["tenant", "entity_type", "entity_id"],
                        name="audit_audit_tenant__f6fa3d_idx",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("login_succeeded", "Inicio de sesión"),
                            ("login_failed", "Inicio de sesión fallido"),
                            ("logout", "Cierre de sesión"),
                            ("password_changed", "Cambio de contraseña"),
                            ("tenant_switched", "Cambio de empresa"),
                            ("invitation_accepted", "Invitación aceptada"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email", models.CharField(blank=True, default="", max_length=254)),
                ("tenant_id_snapshot", models.BigIntegerField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de seguridad",
                "verbose_name_plural": "Eventos de seguridad",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["kind", "-created_at"],
                        name="audit_secur_kind_5ba4de_idx",
                    ),
                    models.Index(
                        fields=["email", "-created_at"],
                        name="audit_secur_email_720882_idx",
                    ),
                ],
            },
        ),
    ]
