# Generated by Django 6.0.4 on 2026-10-09 13:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
        ("customers", "0003_alter_customer_address_alter_customer_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="customers.customer",
                verbose_name="cliente",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="descuento",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(verbose_name="vencimiento"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("quote", "Cotización"), ("invoice", "Factura")],
                default="invoice",
                max_length=10,
                verbose_name="tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(verbose_name="fecha de emisión"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="notas"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(max_length=30, verbose_name="número"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("sent", "Enviada"),
                    ("paid", "Pagada"),
                    ("overdue", "Vencida"),
                    ("cancelled", "Cancelada"),
                ],
                default="draft",
                max_length=10,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="subtotal",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="impuestos",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="total",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="descripción"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="position",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="cargo"),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="impuestos"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="IVA %"
            ),
        ),
    ]
