# Generated by Django 6.0.4 on 2026-10-08 21:28

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de ciudadanía"),
                            ("NIT", "NIT"),
                            ("CE", "Cédula de extranjería"),
                            ("PP", "Pasaporte"),
                        ],
                        default="CC",
                        max_length=5,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activo"), ("inactive", "Inactivo")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["first_name", "last_name", "id"],
                "abstract": False,
                "base_manager_name": "all_tenants",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
