# Generated by Django 6.0.4 on 2026-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="dirección"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="ciudad"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="razón social"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="document_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="número de documento",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("CC", "Cédula de ciudadanía"),
                    ("NIT", "NIT"),
                    ("CE", "Cédula de extranjería"),
                    ("PP", "Pasaporte"),
                ],
                default="CC",
                max_length=5,
                verbose_name="tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="apellido"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="notas"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="teléfono"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[("active", "Activo"), ("inactive", "Inactivo")],
                default="active",
                max_length=10,
                verbose_name="estado",
            ),
        ),
    ]
