# Generated by Django 6.0.4 on 2026-10-10 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cash", "0001_initial"),
        ("sales", "0001_initial"),
        ("tenancy", "0002_alter_location_address_alter_location_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cashmovement",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sales.sale",
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="cashregister",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.location",
                verbose_name="sucursal",
            ),
        ),
        migrations.AddField(
            model_name="cashregister",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="opened_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="register",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="cash.cashregister",
                verbose_name="caja",
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="cash.cashsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashregister",
            constraint=models.UniqueConstraint(
                fields=("tenant", "location", "name"), name="register_unique_name"
            ),
        ),
        migrations.AddIndex(
            model_name="cashsession",
            index=models.Index(
                fields=["tenant", "status"], name="cash_cashse_tenant__92c1a6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("register",),
                name="cash_one_open_session_per_register",
                violation_error_message="Esta caja ya tiene un turno abierto.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("tenant", "opened_by"),
                name="cash_one_open_session_per_user",
                violation_error_message="Ya tienes un turno de caja abierto.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("amount__gt", 0), ("type__in", ["sale", "income"])),
                    models.Q(
                        ("amount__lt", 0),
                        ("type__in", ["void", "expense", "withdrawal"]),
                    ),
                    _connector="OR",
                ),
                name="cash_movement_sign_matches_type",
            ),
        ),
    ]
