# Generated by Django 6.0.4 on 2026-10-10 02:41

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0002_alter_location_address_alter_location_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("doc_type", models.CharField(max_length=30)),
                ("prefix", models.CharField(blank=True, default="", max_length=10)),
                ("next_value", models.PositiveBigIntegerField(default=1)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenancy.location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consecutivo",
                "verbose_name_plural": "Consecutivos",
                "abstract": False,
                "base_manager_name": "all_tenants",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "location", "doc_type"),
                        name="sequence_unique_per_location",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
