# Generated by Django 6.0.4 on 2026-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="dirección"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="ciudad"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                choices=[
                    ("admin", "Administración"),
                    ("sales", "Ventas"),
                    ("operations", "Operaciones"),
                    ("finance", "Finanzas"),
                    ("it", "Tecnología"),
                    ("hr", "Recursos Humanos"),
                    ("other", "Otro"),
                ],
                default="other",
                max_length=20,
                verbose_name="área",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="document_number",
            field=models.CharField(max_length=20, verbose_name="número de documento"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("CC", "Cédula de ciudadanía"),
                    ("CE", "Cédula de extranjería"),
                    ("PP", "Pasaporte"),
                ],
                default="CC",
                max_length=5,
                verbose_name="tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(verbose_name="fecha de ingreso"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="apellido"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="notas"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="teléfono"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(max_length=100, verbose_name="cargo"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="salario",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[("active", "Activo"), ("inactive", "Inactivo")],
                default="active",
                max_length=10,
                verbose_name="estado",
            ),
        ),
    ]
