# Generated by Django 6.0.4 on 2026-10-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0002_alter_location_address_alter_location_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="código")),
                ("name", models.CharField(max_length=60, verbose_name="nombre")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="descripción",
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vacío = por definir.",
                        max_digits=12,
                        null=True,
                        verbose_name="precio mensual",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="COP", max_length=3, verbose_name="moneda"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="visible en la página de precios"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "sort",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Planes",
                "ordering": ["sort", "code"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "En prueba"),
                            ("active", "Activa"),
                            ("past_due", "Pago pendiente"),
                            ("canceled", "Cancelada"),
                        ],
                        default="trialing",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="inicio")),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="fin del período / renovación",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fin de la prueba"
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelada el"
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="referencia de la pasarela de pago",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=60, verbose_name="funcionalidad")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionalidad del plan",
                "verbose_name_plural": "Funcionalidades del plan",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "key"), name="planfeature_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=60, verbose_name="límite")),
                (
                    "value",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Vacío = ilimitado.",
                        null=True,
                        verbose_name="valor",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limits",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Límite del plan",
                "verbose_name_plural": "Límites del plan",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "key"), name="planlimit_unique"
                    )
                ],
            },
        ),
    ]
