# Generated by Django 6.0.4 on 2026-04-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'name')},
        ),
    ]
