# Generated by Django 6.0.4 on 2026-10-09 19:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004b_units_and_item_data"),
        ("tenancy", "0002_alter_location_address_alter_location_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "base_manager_name": "all_tenants",
                "ordering": ["name", "id"],
                "verbose_name": "Ítem",
                "verbose_name_plural": "Ítems",
            },
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="category_unique_name_per_tenant",
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="product_unique_code_per_tenant",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="catalog_pro_tenant__e1f8c5_idx",
        ),
        migrations.AlterField(
            model_name="item",
            name="avg_cost",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="costo por unidad",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="catalog.category",
                verbose_name="categoría",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="minimum_stock",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="existencia mínima",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="precio de venta",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="stock",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="existencia",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="catalog.unitofmeasure",
                verbose_name="unidad",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["tenant", "kind", "is_active"],
                name="catalog_ite_tenant__1612b5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("tenant", "kind", "name"),
                name="category_unique_name_per_kind",
                violation_error_message="Ya existe una categoría con este nombre.",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"),
                name="item_unique_code_per_tenant",
                violation_error_message="Ya existe un ítem con este código.",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "raw_material"), ("is_sellable", True), _connector="OR"
                ),
                name="item_products_are_sellable",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "service"), _negated=True),
                    models.Q(("stock", 0), ("minimum_stock", 0)),
                    _connector="OR",
                ),
                name="item_service_without_stock",
            ),
        ),
        migrations.RemoveField(
            model_name="item",
            name="product_type",
        ),
    ]
