# Generated by Django 6.0.4 on 2026-10-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_grant_view_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="consume_on_sale",
            field=models.BooleanField(
                default=False, verbose_name="descuenta ingredientes al vender"
            ),
        ),
    ]
