# Generated by Django 6.0.4 on 2026-10-10 03:26

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0007_item_consume_on_sale"),
        ("tenancy", "0002_alter_location_address_alter_location_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="catalog.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Existencia por sucursal",
                "abstract": False,
                "base_manager_name": "all_tenants",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "location"), name="stock_level_unique"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("opening", "Saldo inicial"),
                            ("purchase", "Compra"),
                            ("sale", "Venta"),
                            ("sale_void", "Anulación de venta"),
                            ("production_consume", "Consumo en producción"),
                            ("production_output", "Producción"),
                            ("waste", "Merma"),
                            ("adjustment_in", "Ajuste (sobrante)"),
                            ("adjustment_out", "Ajuste (faltante)"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Con signo, en la unidad del ítem: positivo entra, negativo sale.",
                        max_digits=16,
                        verbose_name="cantidad",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="costo unitario"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="costo total"
                    ),
                ),
                ("balance_after", models.DecimalField(decimal_places=4, max_digits=16)),
                (
                    "avg_cost_after",
                    models.DecimalField(decimal_places=4, max_digits=16),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("source_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "source_label",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="motivo"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="catalog.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de inventario",
                "verbose_name_plural": "Movimientos de inventario",
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_tenants",
                "indexes": [
                    models.Index(
                        fields=["tenant", "item", "created_at"],
                        name="inventory_s_tenant__674c6e_idx",
                    ),
                    models.Index(
                        fields=["tenant", "type", "created_at"],
                        name="inventory_s_tenant__e4ffab_idx",
                    ),
                    models.Index(
                        fields=["tenant", "source_type", "source_id"],
                        name="inventory_s_tenant__8370d1_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("quantity__gt", 0),
                                (
                                    "type__in",
                                    [
                                        "opening",
                                        "purchase",
                                        "sale_void",
                                        "production_output",
                                        "adjustment_in",
                                    ],
                                ),
                            ),
                            models.Q(
                                ("quantity__lt", 0),
                                (
                                    "type__in",
                                    [
                                        "sale",
                                        "production_consume",
                                        "waste",
                                        "adjustment_out",
                                    ],
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="stock_movement_sign_matches_type",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
