# Generated by Django 6.0.4 on 2026-10-08 21:28

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=200)),
                (
                    "contact_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("NIT", "NIT"),
                            ("CC", "Cédula de ciudadanía"),
                            ("CE", "Cédula de extranjería"),
                            ("PP", "Pasaporte"),
                        ],
                        default="NIT",
                        max_length=5,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("materials", "Materiales e insumos"),
                            ("services", "Servicios"),
                            ("technology", "Tecnología"),
                            ("logistics", "Logística y transporte"),
                            ("marketing", "Marketing y publicidad"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activo"), ("inactive", "Inactivo")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["company_name", "id"],
                "abstract": False,
                "base_manager_name": "all_tenants",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("document_number", ""), _negated=True),
                        fields=("tenant", "document_type", "document_number"),
                        name="supplier_unique_document_per_tenant",
                        violation_error_message="Ya existe un proveedor con este documento.",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
    ]
