# Generated by Django 6.0.4 on 2026-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="dirección"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="category",
            field=models.CharField(
                choices=[
                    ("materials", "Materiales e insumos"),
                    ("services", "Servicios"),
                    ("technology", "Tecnología"),
                    ("logistics", "Logística y transporte"),
                    ("marketing", "Marketing y publicidad"),
                    ("other", "Otro"),
                ],
                default="other",
                max_length=20,
                verbose_name="categoría",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="ciudad"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="company_name",
            field=models.CharField(max_length=200, verbose_name="razón social"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="contacto"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="document_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="número de documento",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("NIT", "NIT"),
                    ("CC", "Cédula de ciudadanía"),
                    ("CE", "Cédula de extranjería"),
                    ("PP", "Pasaporte"),
                ],
                default="NIT",
                max_length=5,
                verbose_name="tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="notas"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="teléfono"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="status",
            field=models.CharField(
                choices=[("active", "Activo"), ("inactive", "Inactivo")],
                default="active",
                max_length=10,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="website",
            field=models.URLField(blank=True, default="", verbose_name="sitio web"),
        ),
    ]
