# Generated by Django 6.0.4 on 2026-10-10 03:26

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0007_item_consume_on_sale"),
        ("suppliers", "0002_alter_supplier_address_alter_supplier_category_and_more"),
        ("tenancy", "0002_alter_location_address_alter_location_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=30, verbose_name="número")),
                (
                    "supplier_invoice",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="factura del proveedor",
                    ),
                ),
                ("received_on", models.DateField(verbose_name="fecha de recepción")),
                ("total", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notas"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.location",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="suppliers.supplier",
                        verbose_name="proveedor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
                "ordering": ["-received_on", "-id"],
                "abstract": False,
                "base_manager_name": "all_tenants",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="cantidad"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        verbose_name="costo por unidad de compra",
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=16)),
                ("base_quantity", models.DecimalField(decimal_places=4, max_digits=16)),
                (
                    "base_unit_cost",
                    models.DecimalField(decimal_places=4, max_digits=16),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.unitofmeasure",
                        verbose_name="unidad",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchasing.purchasereceipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de compra",
                "ordering": ["id"],
                "abstract": False,
                "base_manager_name": "all_tenants",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="purchasereceipt",
            constraint=models.UniqueConstraint(
                fields=("tenant", "location", "number"), name="purchase_unique_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0), ("unit_cost__gte", 0)),
                name="purchase_line_valid",
            ),
        ),
    ]
